---
name: Deploy Website

on:
  push:
    paths:
      - '.github/workflows/web.yaml'
      - 'web/**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment,
# skipping runs queued between the run in-progress and latest queued.
# Cancel in-progress runs to prioritize the latest deployment.
concurrency:
  group: 'deploy-web'
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-linux:
    name: Deploy website
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mistweaverco/opendeck-ajazz-ci:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache Bun
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: linux-web-bun-${{ hashFiles('web/bun.lock') }}
          restore-keys: |
            linux-web-bun-${{ hashFiles('web/bun.lock') }}
      - name: Install dependencies
        run: cd web && bun install --frozen-lockfile
      - name: Create Website
        run: cd web && bun run build --frozen-lockfile
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'web/build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
